deployment:
tasks:
- export DEPLOYPATH=/home/igmengct/public_html/
-- export PROJECTROOT=/home/igmengct/repositories/fcs
- /bin/cp $PROJECTROOT/website/* $DEPLOYPATH
- /bin/cp $PROJECTROOT/miscellanious/* $DEPLOYPATH